version: '3.1'
services:
  web:
    image: docker.localhost/drupal:11.3.2
    ports:
      - 8080:80
    restart: always
    volumes:
      - ./drupal:/var/www/drupal
  drupal-site-mysql:
    image: mysql:8.4.8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: drupal-site
      MYSQL_USER: drupal
      MYSQL_PASSWORD: password123
    volumes:
      - ./mysql:/var/lib/mysql
